### ISSUE TITLE
BVV

### ISSUE THREAD

**Issue by bartvanvliet** [JohanDeLijser/Pagebuilder#1]
![image](https://user-images.githubusercontent.com/1766076/49735925-e86cdb00-fc88-11e8-856a-ee2c077fa52b.png)

**Comment by jeroenfrenken** [comment]
@JohanDeLijser lekker bezig

**Comment by jeroenfrenken** [comment]
@JohanDeLijser @Kapulara joejoe

**Comment by wesleyvdkop** [comment]
Asje me nou

**Comment by jeroenfrenken** [comment]
Joooo Han hoe gaat het met je project ?

**Comment by bartvanvliet** [comment]
> Joooo Han hoe gaat het met je project ?

Johan slaapt nog

**Comment by jeroenfrenken** [comment]
ooh vandaar

**Comment by wesleyvdkop** [comment]
Johan heeft geen zorge: "Init project -- 8 days ago"
